# Generated by Django 4.2 on 2023-05-01 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='risk_profile',
            field=models.CharField(choices=[('C', 'Conservador'), ('M', 'Moderado'), ('A', 'Arrojado')], max_length=1),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_done', models.DateTimeField(auto_now_add=True)),
                ('quantity_stock', models.PositiveIntegerField()),
                ('unite_price', models.FloatField()),
                ('type_of', models.CharField(choices=[('C', 'Compra'), ('V', 'Venda')], max_length=1)),
                ('brokerage', models.FloatField()),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_wallet.investor')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_wallet.stock')),
            ],
        ),
    ]
