# Generated by Django 4.1.7 on 2023-05-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_wallet', '0003_alter_stock_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='cnpj',
            field=models.CharField(max_length=18),
        ),
    ]
