# Generated by Django 4.2.1 on 2023-05-10 01:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_wallet', '0005_alter_transaction_date_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_done',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
